### ISSUE TITLE
glibc_2.29

### ISSUE THREAD

**Issue by blancoklips** [dyc3/steamguard-cli#139] opened 2022-03-25 21:05 UTC
After installing the .deb file with dpkg when running steamguard in the terminal it spits out: steamguard: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by steamguard). Is there a library missing?

**Comment by dyc3** [comment] 2022-03-26 13:08
duplicate of #111, please make a comment over there.

**Closed by dyc3** 2022-03-26 13:08 UTC
Labels: duplicate
