### ISSUE TITLE
System.ArgumentOutOfRangeException when phone number change is requested.

### ISSUE THREAD

**Issue by melvyn2** [dyc3/steamguard-cli#38] opened 2018-12-15 02:32 UTC
see [#29 (comment)](https://github.com/dyc3/steamguard-cli/issues/29#issuecomment-447530252)

**Comment by k4rli** [comment] 2020-05-06 12:25
Encountered same when trying to change email address. Only solution is to remove authenticator -> change email -> readd authenticator.

**Comment by dyc3** [comment] 2020-05-06 12:48
Could you provide steps to reproduce this?

**Comment by k4rli** [comment] 2020-05-06 12:59
1. Go to [change email](https://help.steampowered.com/en/wizard/HelpChangeEmail?redir=store/account/)
2. Choose *Send a confirmation to my Steam Mobile app*
3. It should say *Waiting for you to confirm using the Steam app...*.
  - Run `steamguard accept-all`
  - Fails and prints  
```
Accepting Confirmations on {REDACTED_USERNAME}
WARNING: counts of confirmations matches and descriptions matches are not equal: ${confirmations.Count} != ${confDescs.Count}

Unhandled Exception:
System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.
Parameter name: i) ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
{... stacktrace from #29 appears} 
```

Same result when running `steamguard trade`

**Comment by chaorace** [comment] 2021-07-16 14:29
I am able to replicate the issue when attempting a phone number change via [this page](https://store.steampowered.com/phone/remove_confirm_mobileconf), see stacktrace below. I'm guessing that `steamguard-cli` doesn't know what to do for non-trade confirmations?

```
~ λ steamguard accept-all
Accepting Confirmations on chaokarate
WARNING: counts of confirmations matches and descriptions matches are not equal: ${confirmations.Count} != ${confDescs.Count}

Unhandled Exception:
System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.
Parameter name: i) ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00004] in <1af2426e91d1474d92e5d471c4ca8f95>:0 
  at SteamAuth.SteamGuardAccount.parseConfirmationHTML (System.String response) [0x00123] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationInternal (System.String response) [0x00000] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationsAsync () [0x000bf] in <3504a544933d402baf95fef922a19bbd>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at SteamGuard.Program.AcceptAllTrades (System.String user, System.String passkey) [0x0016d] in <5f8fb4c5eb9b4d21b842b4f6add771aa>:0 
  at SteamGuard.Program.Main (System.String[] args) [0x0043c] in <5f8fb4c5eb9b4d21b842b4f6add771aa>:0 
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00004] in <1af2426e91d1474d92e5d471c4ca8f95>:0 
  at SteamAuth.SteamGuardAccount.parseConfirmationHTML (System.String response) [0x00123] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationInternal (System.String response) [0x00000] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationsAsync () [0x000bf] in <3504a544933d402baf95fef922a19bbd>:0 <---

[ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.
Parameter name: i) ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00004] in <1af2426e91d1474d92e5d471c4ca8f95>:0 
  at SteamAuth.SteamGuardAccount.parseConfirmationHTML (System.String response) [0x00123] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationInternal (System.String response) [0x00000] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationsAsync () [0x000bf] in <3504a544933d402baf95fef922a19bbd>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at SteamGuard.Program.AcceptAllTrades (System.String user, System.String passkey) [0x0016d] in <5f8fb4c5eb9b4d21b842b4f6add771aa>:0 
  at SteamGuard.Program.Main (System.String[] args) [0x0043c] in <5f8fb4c5eb9b4d21b842b4f6add771aa>:0 
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00004] in <1af2426e91d1474d92e5d471c4ca8f95>:0 
  at SteamAuth.SteamGuardAccount.parseConfirmationHTML (System.String response) [0x00123] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationInternal (System.String response) [0x00000] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationsAsync () [0x000bf] in <3504a544933d402baf95fef922a19bbd>:0 <---
```

**Comment by chaorace** [comment] 2021-07-16 14:30
I am able to replicate the issue when attempting a phone number change via [this page](https://store.steampowered.com/phone/remove_confirm_mobileconf), see stacktrace below. I'm guessing that `steamguard-cli` doesn't know what to do for non-trade confirmations?

```
~ λ steamguard accept-all
Accepting Confirmations on <REDACTED>
WARNING: counts of confirmations matches and descriptions matches are not equal: ${confirmations.Count} != ${confDescs.Count}

Unhandled Exception:
System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.
Parameter name: i) ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00004] in <1af2426e91d1474d92e5d471c4ca8f95>:0 
  at SteamAuth.SteamGuardAccount.parseConfirmationHTML (System.String response) [0x00123] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationInternal (System.String response) [0x00000] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationsAsync () [0x000bf] in <3504a544933d402baf95fef922a19bbd>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at SteamGuard.Program.AcceptAllTrades (System.String user, System.String passkey) [0x0016d] in <5f8fb4c5eb9b4d21b842b4f6add771aa>:0 
  at SteamGuard.Program.Main (System.String[] args) [0x0043c] in <5f8fb4c5eb9b4d21b842b4f6add771aa>:0 
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00004] in <1af2426e91d1474d92e5d471c4ca8f95>:0 
  at SteamAuth.SteamGuardAccount.parseConfirmationHTML (System.String response) [0x00123] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationInternal (System.String response) [0x00000] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationsAsync () [0x000bf] in <3504a544933d402baf95fef922a19bbd>:0 <---

[ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.
Parameter name: i) ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00004] in <1af2426e91d1474d92e5d471c4ca8f95>:0 
  at SteamAuth.SteamGuardAccount.parseConfirmationHTML (System.String response) [0x00123] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationInternal (System.String response) [0x00000] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationsAsync () [0x000bf] in <3504a544933d402baf95fef922a19bbd>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <efe941bb62534dc3a62ceb1a818964a0>:0 
  at SteamGuard.Program.AcceptAllTrades (System.String user, System.String passkey) [0x0016d] in <5f8fb4c5eb9b4d21b842b4f6add771aa>:0 
  at SteamGuard.Program.Main (System.String[] args) [0x0043c] in <5f8fb4c5eb9b4d21b842b4f6add771aa>:0 
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00004] in <1af2426e91d1474d92e5d471c4ca8f95>:0 
  at SteamAuth.SteamGuardAccount.parseConfirmationHTML (System.String response) [0x00123] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationInternal (System.String response) [0x00000] in <3504a544933d402baf95fef922a19bbd>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmationsAsync () [0x000bf] in <3504a544933d402baf95fef922a19bbd>:0 <---
```

**Comment by chaorace** [comment] 2021-07-16 14:37
It seems that the issue is, associated with the [parseConfirmationHTML](https://github.com/dyc3/SteamAuth/blob/e0619528fbe8f4c6f74135283b3f991219e73cf4/SteamAuth/SteamGuardAccount.cs#L154) function of the companion SteamAuth library.

That repo has the issues tab disabled, so I guess this will have to serve as the main place to track progress on fixing the library bug.

**Comment by dyc3** [comment] 2021-07-17 23:11
Yeah, I'm currently working on rewriting this project in rust. Progress is very slow. See #55. Because of that, I'm not planning to fix this bug in the current C# code, but I will accept pull requests.

**Comment by dyc3** [comment] 2021-09-01 12:55
Closing because no longer relevant.

**Closed by dyc3** 2021-09-01 12:55 UTC
Labels: bug
