### ISSUE TITLE
Unknown add authenticator status code: 2

### ISSUE THREAD

**Issue by RunningDroid** [dyc3/steamguard-cli#116] opened 2021-12-11 03:12 UTC
When running `steamguard-cli setup` it fails with `ERROR - Failed to link authenticator. Account has not been linked. Unknown add authenticator status code: 2`

Full log:
```
INFO - reading manifest from /home/runningdroid/.config/steamguard-cli/maFiles
ERROR - Did not find manifest in /home/runningdroid/.config/steamguard-cli/maFiles
Would you like to create a manifest in /home/runningdroid/.config/steamguard-cli/maFiles ? [Yn]
INFO - Saving manifest and accounts...
Log in to the account that you want to link to steamguard-cli
Username: RunningDroid
Password:
You should have received an email with a code.
Enter code: xxxxx
ERROR - Failed to link authenticator. Account has not been linked. Unknown add authenticator status code: 2
```

**Comment by dyc3** [comment] 2021-12-11 03:49
I need some additional information so we can document the behavior of the steam API.

- Do you have a phone number linked to your account?
- Is the time on your PC set correctly?

Is there any chance you could try this again with the `trace` log level `-vv`? **Keep in mind that there's sensitive info at that log level.** I'm looking specifically for log lines:
- `raw add authenticator response: `
- `raw finalize authenticator response: `

**Comment by RunningDroid** [comment] 2021-12-11 05:16
I don't have a phone number linked to my account and my computer's time is set correctly.
It looks like steamguard-cli only got far enough to log `raw add authenticator response: {"response":{"status":2}}`:

```
INFO - reading manifest from /home/runningdroid/.config/steamguard-cli/maFiles
DEBUG - loading manifest: "/home/runningdroid/.config/steamguard-cli/maFiles/manifest.json"
Log in to the account that you want to link to steamguard-cli
Username: RunningDroid
Password:
DEBUG - password is present
TRACE - UserLogin::login
TRACE - SteamApiClient::update_session
TRACE - making request: GET https://steamcommunity.com/login?oauth_client_id=DE45CD61&oauth_scope=read_profile%20write_profile%20read_client%20write_client
TRACE - Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("steamcommunity.com")), port: None, path: "/login", query: Some("oauth_client_id=DE45CD61&oauth_scope=read_profile%20write_profile%20read_client%20write_client"), fragment: None }, status: 200, headers: {"server": "nginx", "content-type": "text/html; charset=UTF-8", "x-frame-options": "DENY", "content-security-policy": "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://community.cloudflare.steamstatic.com/ https://cdn.cloudflare.steamstatic.com/steamcommunity/public/assets/ https://api.steampowered.com/ *.google-analytics.com https://www.google.com https://www.gstatic.com https://apis.google.com https://recaptcha.net https://www.gstatic.cn/recaptcha/; object-src 'none'; connect-src 'self' https://community.cloudflare.steamstatic.com/ https://store.steampowered.com/ wss://community.steam-api.com/websocket/ https://api.steampowered.com/ *.google-analytics.com https://*.valvesoftware.com https://*.steambeta.net https://*.steamcontent.com https://steambroadcast.akamaized.net https://steambroadcastchat.akamaized.net https://broadcast.st.dl.bscstorage.net https://broadcast.st.dl.eccdnx.com http://127.0.0.1:27060 ws://127.0.0.1:27060; frame-ancestors 'self' https://steamloopback.host ;", "expires": "Mon, 26 Jul 1997 05:00:00 GMT", "cache-control": "no-cache", "set-cookie": "sessionid=9f29d4f9bc21599ac97d860a; Path=/; Secure; SameSite=None", "set-cookie": "steamCountry=US%7C7107d1806280ebd8067aee7b82120fdb; Path=/; Secure; HttpOnly; SameSite=None", "vary": "Accept-Encoding", "connection": "keep-alive", "date": "Sat, 11 Dec 2021 04:50:57 GMT"} }
TRACE - cookies: Jar(REDACTED)
TRACE - making request: POST https://steamcommunity.com/login/getrsakey
TRACE - captchagid: -1
TRACE - captcha_text:
TRACE - twofactorcode:
TRACE - emailauth:
TRACE - making request: POST https://steamcommunity.com/login/dologin
TRACE - raw login response: {"success":false,"requires_twofactor":false,"message":"","emailauth_needed":true,"emaildomain":"gmail.com","emailsteamid":"76561198048824167"}
You should have received an email with a code.
Enter code: 487rh
TRACE - UserLogin::login
TRACE - SteamApiClient::update_session
TRACE - making request: GET https://steamcommunity.com/login?oauth_client_id=DE45CD61&oauth_scope=read_profile%20write_profile%20read_client%20write_client
TRACE - Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("steamcommunity.com")), port: None, path: "/login", query: Some("oauth_client_id=DE45CD61&oauth_scope=read_profile%20write_profile%20read_client%20write_client"), fragment: None }, status: 200, headers: {"server": "nginx", "content-type": "text/html; charset=UTF-8", "x-frame-options": "DENY", "content-security-policy": "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://community.cloudflare.steamstatic.com/ https://cdn.cloudflare.steamstatic.com/steamcommunity/public/assets/ https://api.steampowered.com/ *.google-analytics.com https://www.google.com https://www.gstatic.com https://apis.google.com https://recaptcha.net https://www.gstatic.cn/recaptcha/; object-src 'none'; connect-src 'self' https://community.cloudflare.steamstatic.com/ https://store.steampowered.com/ wss://community.steam-api.com/websocket/ https://api.steampowered.com/ *.google-analytics.com https://*.valvesoftware.com https://*.steambeta.net https://*.steamcontent.com https://steambroadcast.akamaized.net https://steambroadcastchat.akamaized.net https://broadcast.st.dl.bscstorage.net https://broadcast.st.dl.eccdnx.com http://127.0.0.1:27060 ws://127.0.0.1:27060; frame-ancestors 'self' https://steamloopback.host ;", "expires": "Mon, 26 Jul 1997 05:00:00 GMT", "cache-control": "no-cache", "set-cookie": "steamLoginSecure=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/", "set-cookie": "steamLogin=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/", "vary": "Accept-Encoding", "connection": "keep-alive", "date": "Sat, 11 Dec 2021 04:51:13 GMT"} }
TRACE - cookies: Jar(REDACTED)
TRACE - making request: POST https://steamcommunity.com/login/getrsakey
TRACE - captchagid: -1
TRACE - captcha_text:
TRACE - twofactorcode:
TRACE - emailauth: 487rh
TRACE - making request: POST https://steamcommunity.com/login/dologin
TRACE - raw login response: {"success":true,"requires_twofactor":false,"redirect_uri":"steammobile:\/\/mobileloginsucceeded","login_complete":true,"oauth":"{\"steamid\":\"76561198048824167\",\"account_name\":\"runningdroid\",\"oauth_token\":\"REDACTED\",\"wgtoken\":\"REDACTED\",\"wgtoken_secure\":\"REDACTED\",\"webcookie\":\"REDACTED\"}"}
TRACE - SteamApiClient::build_session
TRACE - making request: POST https://api.steampowered.com/ITwoFactorService/AddAuthenticator/v0001
TRACE - raw add authenticator response: {"response":{"status":2}}
ERROR - Failed to link authenticator. Account has not been linked. Unknown add authenticator status code: 2
```

**Comment by dyc3** [comment] 2021-12-11 07:14
I don't see anything wrong here, except it's returning status 2 for some reason. I think it might have something to do with not having a phone number linked. Try adding a phone number, and then running setup again.

**Comment by dyc3** [comment] 2021-12-11 19:43
After doing a little bit of research, it turns out that status code 2 just means "generic failure", with no other explanation. 

https://github.com/ValvePython/steam/blob/0a6d152e514f0f0cfd8f8e17a8d86341e85aff23/steam/enums/common.py#L8

So this is probably still Steam's fault. I'll leave this issue open because we should pull in this enum to give better error messages.

**Comment by RunningDroid** [comment] 2021-12-12 03:06
> I think it might have something to do with not having a phone number linked. Try adding a phone number, and then running setup again.

I added my number to my account and steamguard-cli progressed further, then got stuck (strace said it was stuck on a futex.)
I killed it with SIGINT and it seems to work fine now (I used it to login to steam in a private window just to make sure.)

Log snippet:
```
Authenticator has not yet been linked. Before continuing with finalization, please take the time to write down your revocation code: R55281
Press any key to continue...
DEBUG - attempting link finalization
Enter SMS code: 00000
TRACE - making request: POST https://api.steampowered.com/ITwoFactorService/FinalizeAddAuthenticator/v0001
TRACE - raw finalize authenticator response: {"response":{"success":true,"want_more":false,"server_time":"1639271752","status":2}}
INFO - finalize response status: 2
Authenticator finalized.
INFO - Saving manifest and accounts...
DEBUG - saving runningdroid.maFile
^C
```

**Comment by dyc3** [comment] 2021-12-12 03:45
> strace said it was stuck on a futex.

That's actually super useful to know. That hanging bug is really annoying and really hard to track down. I can never seem to reliably reproduce it. I'll go ahead and reopen #107.

**Comment by dyc3** [comment] 2022-01-02 17:06
The error message for this status code has been updated. Closing.

**Closed by dyc3** 2022-01-02 17:06 UTC
Labels: bug
