### ISSUE TITLE
ArgumentOutOfRangeException when viewing trades

### ISSUE THREAD

**Issue by xitero** [dyc3/steamguard-cli#17] opened 2017-05-31 03:10 UTC
I get the following error:

`System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00015] in <2fef7234205a4a009fe5995569c314ee>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmations () [0x0010a] in <e9380748a38f4f39b77c7f4ae9afdc4b>:0 
  at SteamGuard.Program.processConfirmations (SteamAuth.SteamGuardAccount account) [0x00182] in <8105e53619334720bc024ca58d8d1f87>:0 
  at SteamGuard.Program.Trade (System.String user, System.String passkey) [0x000cf] in <8105e53619334720bc024ca58d8d1f87>:0 
  at SteamGuard.Program.Main (System.String[] args) [0x003e4] in <8105e53619334720bc024ca58d8d1f87>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00015] in <2fef7234205a4a009fe5995569c314ee>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmations () [0x0010a] in <e9380748a38f4f39b77c7f4ae9afdc4b>:0 
  at SteamGuard.Program.processConfirmations (SteamAuth.SteamGuardAccount account) [0x00182] in <8105e53619334720bc024ca58d8d1f87>:0 
  at SteamGuard.Program.Trade (System.String user, System.String passkey) [0x000cf] in <8105e53619334720bc024ca58d8d1f87>:0 
  at SteamGuard.Program.Main (System.String[] args) [0x003e4] in <8105e53619334720bc024ca58d8d1f87>:0 `

**Comment by dyc3** [comment] 2017-05-31 11:59
Appears to be a duplicate of #15 

Could you provide your distro and steam guard cli version?

**Comment by xitero** [comment] 2017-05-31 20:05
It's the same error, but the code is different.
I use XFCE Antergos (Arch Linux) and the latest version of steamguard-cli.

**Comment by dyc3** [comment] 2017-05-31 20:55
I'm going to create a Antergos VM to try to recreate this. Further discussion will be in #15

**Closed by dyc3** 2017-05-31 20:55 UTC
Labels: duplicate
