### ISSUE TITLE
Can't confirm trades

### ISSUE THREAD

**Issue by Lyapsus** [dyc3/steamguard-cli#169] opened 2022-09-12 18:48 UTC
`thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/tui.rs:262:22` after enter in `steamguard trade`

**Comment by dyc3** [comment] 2022-09-12 18:53
This specific bug is already fixed on master. The cause is steam is not returning any confirmations for the specified account. Make sure you are specifying the correct account with `-u`.

**Closed by dyc3** 2022-09-12 18:53 UTC

**Comment by Lyapsus** [comment] 2022-09-12 19:16
Well I made sure, there is indeed zero visible confirmations
