### ISSUE TITLE
ArgumentOutOfRangeException when viewing trades

### ISSUE THREAD

**Issue by bontibon** [dyc3/steamguard-cli#15] opened 2017-05-17 00:17 UTC
Version: v0.2.2.0

```
% ./steamguard trade
Retrieving trade confirmations...

Unhandled Exception:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00015] in <2fef7234205a4a009fe5995569c314ee>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmations () [0x0010a] in <6a95291e97294c488544cad5c1101962>:0 
  at SteamGuard.Program.processConfirmations (SteamAuth.SteamGuardAccount account) [0x00182] in <f67e175915d940a0985109e2a0400890>:0 
  at SteamGuard.Program.Trade (System.String user) [0x000c3] in <f67e175915d940a0985109e2a0400890>:0 
  at SteamGuard.Program.Main (System.String[] args) [0x0038a] in <f67e175915d940a0985109e2a0400890>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
  at System.Text.RegularExpressions.MatchCollection.get_Item (System.Int32 i) [0x00015] in <2fef7234205a4a009fe5995569c314ee>:0 
  at SteamAuth.SteamGuardAccount.FetchConfirmations () [0x0010a] in <6a95291e97294c488544cad5c1101962>:0 
  at SteamGuard.Program.processConfirmations (SteamAuth.SteamGuardAccount account) [0x00182] in <f67e175915d940a0985109e2a0400890>:0 
  at SteamGuard.Program.Trade (System.String user) [0x000c3] in <f67e175915d940a0985109e2a0400890>:0 
  at SteamGuard.Program.Main (System.String[] args) [0x0038a] in <f67e175915d940a0985109e2a0400890>:0 
```

**Comment by dyc3** [comment] 2017-05-18 03:36
Looks like this might be a problem with SteamAuth, but I'll investigate some more soon.

**Comment by dyc3** [comment] 2017-05-19 17:48
Definately a SteamAuth issue. It appears [one of these 3 lines (161-163)](https://github.com/geel9/SteamAuth/blob/825a749f0930da261694860b12634d3297b0cf10/SteamAuth/SteamGuardAccount.cs#L161) failed because there were no regex matches. I'll update the SteamAuth submodule and see if that fixes it.

**Comment by dyc3** [comment] 2017-05-19 17:54
@bontibon Let me know if this happens again, I think this is one of those weird issues that happens one time ever and then it never pops up again.

**Comment by bontibon** [comment] 2017-05-20 16:29
Nope, still not working.

**Comment by dyc3** [comment] 2017-05-21 14:53
Interesting... Is it the same error as you posted before?

**Comment by dyc3** [comment] 2017-05-25 21:32
I can't reproduce this. If anybody else has this problem and knows makes this happen, I'll be happy to fix it. Until then, I'm closing this.

**Comment by dyc3** [comment] 2017-05-31 20:55
Reopening because of #17

**Comment by bontibon** [comment] 2017-06-03 14:30
See underlying issue at geel9/SteamAuth#67. Fixed with the following diff:

```diff
diff --git a/Program.cs b/Program.cs
index c15872d..a551d57 100644
--- a/Program.cs
+++ b/Program.cs
@@ -596,7 +596,9 @@ namespace SteamGuard
                                }
                        }
                        Console.WriteLine("Retrieving trade confirmations...");
-                       var trades = account.FetchConfirmations();
+                       var tradesTask = account.FetchConfirmationsAsync();
+                       tradesTask.Wait();
+                       var trades = tradesTask.Result;
                        var tradeActions = new TradeAction[trades.Length];
                        for (var i = 0; i < tradeActions.Length; i++)
                        {

```

**Comment by dyc3** [comment] 2017-06-04 18:53
Thanks, I'll go implement that right now.

**Closed** 2017-06-04 19:00 UTC
Labels: bug, Not reproducible
